<?php
/**
 * @file
 * Functions to for when the modules is installed or uninstalled.
 */

/**
 * Implements hook_uninstall().
 */
function term_search_uninstall() {
  config_clear('search.settings', 'term_search_indexed_vocabularies');
  db_delete('search_dataset')
    ->condition('type', 'term')
    ->execute();
  db_delete('search_index')
    ->condition('type', 'term')
    ->execute();
}

/**
 * Move term_search settings from variables to config.
 */
function term_search_update_1000() {
  // Migrate variables to config.
  $config = config('search.settings');
  $config->set('term_search_indexed_vocabularies', update_variable_get('term_search_indexed_vocabularies', array()));
  $config->save();

  // Delete variables.
  update_variable_del('term_search_indexed_vocabularies');
}
